# Dependencies
markdown:         redcarpet
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Trinity Cannes
tagline:          "The world's most prestigious film festival comes to Trinity"
baseurl:          /tcafilm

author:
  name:           'Isaac Rowe'
  url:            https://twitter.com/Isaac_rowe1

paginate:         5

# Custom vars
version:          2.1.0

github: irowebbn
repo: https://github.com/irowebbn/tcafilm
