# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Trinity Cannes
tagline:          "The world's most prestigious film festival comes to Trinity "
description:      "The world's most prestigious film festival comes to Trinity"
url:              http://tcafrenchfilm.tk
baseurl:          /

author:
  name:           'Isaac Rowe'
  url:            https://twitter.com/Isaac_rowe1

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/irowebbn/tcafilm
